trigger: none
pr:
 branches:
   include:
     - main
pool: z_automobile_app

variables:
  pythonVersion: '3.12'
  imageRepository: 'automobile-ai-agent'
  imageTag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
  - stage: CI 
    displayName: Build, Test and Scan
    jobs:
      - job:
        steps:
          - script: |
              python3 --version
              python3 -m venv .venv
              .venv/bin/python -m pip install --upgrade pip
              .venv/bin/pip install -r requirements.txt
            displayName: Create venv and install dependencie
# add test but for now we will skip test like unit test, api intigration test,agent intigration test
          - task: Docker@2
            inputs:
              containerRegistry: 'ado-acr'
              repository: '$(imageRepository)'
              command: 'build'
              Dockerfile: '$(dockerfilePath)'
              tags: '$(imageTag)'
          - script: |
              echo "Docker images on agent:"
              docker images
            displayName: 'Verify Docker image'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                trivy image \
                --severity HIGH,CRITICAL \
                --exit-code 1 \
                $(imageRepository):$(imageTag)
            displayName: 'Trivy image security scan'

          - task: Docker@2
            displayName: 'Push image to ACR'
            inputs:
              containerRegistry: 'ado-acr'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(imageTag)'