apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: automobile-agent-secrets
  namespace: automobile-ai
spec:
  provider: azure

  parameters:
    clientID: "424d0659-0ba8-4c18-b906-c31bb0ea8526"
    keyvaultName: "zautomobileskeyvault"
    tenantId: "59f88285-3d7c-4744-9f9d-6bd006bfd6d7"

    objects: |
      array:
        - |
          objectName: LANGFUSE-SECRET-KEY
          objectType: secret
        - |
          objectName: LANGFUSE-PUBLIC-KEY
          objectType: secret
        - |
          objectName: AZURE-SEARCH-API-KEY
          objectType: secret
        - |
          objectName: AZURE-OPENAI-API-KEY
          objectType: secret