apiVersion: v1
kind: Service

metadata:
  name: automobile-ai-agent-service
  namespace: automobile-ai

spec:
  type: LoadBalancer

  selector:
    app: automobile-ai-agent

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
